const express = require('express');
const cors = require('cors');
const app = express();
const PORT = 5000;

app.use(cors());

const sampleData = {
  "s": "200",
  "total_count": "40",
  "data": [
    {
      "order_id": "46372",
      "patient_id": "12359",
      "pat_name": "Harikesh Ramba",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "50 Year",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704093224,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1271",
      "order_status": "New",
      "order_items": "(UG), MRI Abdomen"
    },
    {
      "order_id": "46373",
      "patient_id": "12359",
      "pat_name": "Harikesh Ramba",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "50 Year",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704093224,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1272",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46374",
      "patient_id": "12359",
      "pat_name": "Harikesh Ramba",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "50 Year",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704093225,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1273",
      "order_status": "New",
      "order_items": "MRI Abdomen"
    },
    {
      "order_id": "46375",
      "patient_id": "12482",
      "pat_name": "B/O MINAKI DIGI",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "1 Year 5 Month",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704114191,
      "address": "-, Kolshuli, Kolshuli, West Bengal, India - 144236",
      "referring_panel_name": "",
      "branch_id": "1436",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46376",
      "patient_id": "12483",
      "pat_name": "B/O LALITA DIGI",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "1 Year 5 Month",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704114559,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "",
      "branch_id": "1272",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46377",
      "patient_id": "12484",
      "pat_name": "B/O AMIRA BANO",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "1 Year 5 Month",
      "pat_gender": "Male",
      "date": "01.01.2024",
      "ts": 1704115349,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1437",
      "order_status": "New",
      "order_items": "CBC"
    },
    {
      "order_id": "46381",
      "patient_id": "12120",
      "pat_name": "Anand",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "02.01.2024",
      "ts": 1704195336,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "U R/S, Testosterone,Free"
    },
    {
      "order_id": "46400",
      "patient_id": "12484",
      "pat_name": "B/O AMIRA BANO",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "1 Year 5 Month",
      "pat_gender": "Male",
      "date": "03.01.2024",
      "ts": 1704278661,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "Complete",
      "order_items": "(UG)"
    },
    {
      "order_id": "46404",
      "patient_id": "12046",
      "pat_name": "Mitsuko",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "13 Year",
      "pat_gender": "Female",
      "date": "03.01.2024",
      "ts": 1704288245,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "Testosterone,Free"
    },
    {
      "order_id": "46483",
      "patient_id": "12045",
      "pat_name": "Romsu",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "13 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704370218,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "Follicle Stimulating Hormone"
    },
    {
      "order_id": "46484",
      "patient_id": "11992",
      "pat_name": "Case1",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "-",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704370457,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "U R/S"
    },
    {
      "order_id": "46485",
      "patient_id": "12044",
      "pat_name": "Anup",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "30 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704370668,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46486",
      "patient_id": "11741",
      "pat_name": "Hariom P",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "4 Year 5 Month",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704371362,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "Testosterone,Free"
    },
    {
      "order_id": "46487",
      "patient_id": "12120",
      "pat_name": "Anand",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704371494,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "Testosterone,Free"
    },
    {
      "order_id": "46488",
      "patient_id": "11904",
      "pat_name": "Karanveer Singh",
      "pat_mob_num": "9915258066",
      "email": "",
      "pat_age": "22 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704371983,
      "address": "Chd, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46489",
      "patient_id": "12406",
      "pat_name": "Avinnab Mukund",
      "pat_mob_num": "9044004400",
      "email": "",
      "pat_age": "26 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372132,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "GURMAN SINGH",
      "branch_id": "1433",
      "order_status": "Complete",
      "order_items": "(UG), U R/S, Testing Lab Panel, Testing Lab Panel 2, MRI"
    },
    {
      "order_id": "46490",
      "patient_id": "12406",
      "pat_name": "Avinnab Mukund",
      "pat_mob_num": "9044004400",
      "email": "",
      "pat_age": "26 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372132,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "GURMAN SINGH",
      "branch_id": "1434",
      "order_status": "Complete",
      "order_items": "(UG), U R/S, Testing Lab Panel, Testing Lab Panel 2"
    },
    {
      "order_id": "46491",
      "patient_id": "12406",
      "pat_name": "Avinnab Mukund",
      "pat_mob_num": "9044004400",
      "email": "",
      "pat_age": "26 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372133,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "GURMAN SINGH",
      "branch_id": "1435",
      "order_status": "Complete",
      "order_items": "MRI"
    },
    {
      "order_id": "46492",
      "patient_id": "11886",
      "pat_name": "Devkumar",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "100 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372208,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "(UG)"
    },
    {
      "order_id": "46493",
      "patient_id": "12464",
      "pat_name": "O Dubey",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "56 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372270,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1433",
      "order_status": "Complete",
      "order_items": "GH, Follicle Stimulating Hormone, Testing Lab Panel, MRI"
    },
    {
      "order_id": "46494",
      "patient_id": "12464",
      "pat_name": "O Dubey",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "56 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372270,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1434",
      "order_status": "Complete",
      "order_items": "GH, Follicle Stimulating Hormone, Testing Lab Panel"
    },
    {
      "order_id": "46495",
      "patient_id": "12464",
      "pat_name": "O Dubey",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "56 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704372272,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1435",
      "order_status": "Complete",
      "order_items": "MRI"
    },
    {
      "order_id": "46503",
      "patient_id": "12505",
      "pat_name": "Balbinder",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "-",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704373282,
      "address": "-, Khamar Diar, Khamar Diar, West Bengal, India - 778899",
      "referring_panel_name": "",
      "branch_id": "1436",
      "order_status": "Complete",
      "order_items": "Testing Lab Panel, Testing Lab Panel 2, U R/S, (UG)"
    },
    {
      "order_id": "46505",
      "patient_id": "9829",
      "pat_name": "Anand Kumar Pandit",
      "pat_mob_num": "8436348436",
      "email": "apandit525@getnada.com",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704373573,
      "address": "Near Railway Station, Chawal Patti, Opp Canning Bazar Samiti, canning, South Twenty Four Parganas, West Bengal, India - 743329",
      "referring_panel_name": "",
      "branch_id": "1437",
      "order_status": "Complete",
      "order_items": "GH, Testing Lab Panel 2"
    },
    {
      "order_id": "46507",
      "patient_id": "9829",
      "pat_name": "Anand Kumar Pandit",
      "pat_mob_num": "8436348436",
      "email": "apandit525@getnada.com",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704373781,
      "address": "Near Railway Station, Chawal Patti, Opp Canning Bazar Samiti, canning, South Twenty Four Parganas, West Bengal, India - 743329",
      "referring_panel_name": "",
      "branch_id": "1443",
      "order_status": "New",
      "order_items": "-"
    },
    {
      "order_id": "46508",
      "patient_id": "9829",
      "pat_name": "Anand Kumar Pandit",
      "pat_mob_num": "8436348436",
      "email": "apandit525@getnada.com",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704374079,
      "address": "Near Railway Station, Chawal Patti, Opp Canning Bazar Samiti, canning, South Twenty Four Parganas, West Bengal, India - 743329",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "Pending",
      "order_items": "(UG)"
    },
    {
      "order_id": "46509",
      "patient_id": "9829",
      "pat_name": "Anand Kumar Pandit",
      "pat_mob_num": "8436348436",
      "email": "apandit525@getnada.com",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "04.01.2024",
      "ts": 1704374097,
      "address": "Near Railway Station, Chawal Patti, Opp Canning Bazar Samiti, canning, South Twenty Four Parganas, West Bengal, India - 743329",
      "referring_panel_name": "",
      "branch_id": "1264",
      "order_status": "Pending",
      "order_items": "MRI"
    },
    {
      "order_id": "46584",
      "patient_id": "12046",
      "pat_name": "Mitsuko",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "13 Year",
      "pat_gender": "Female",
      "date": "16.01.2024",
      "ts": 1705417931,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "Complete",
      "order_items": "U R/S"
    },
    {
      "order_id": "46585",
      "patient_id": "12045",
      "pat_name": "Romsu",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "13 Year",
      "pat_gender": "Male",
      "date": "16.01.2024",
      "ts": 1705418273,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "Complete",
      "order_items": "U R/S"
    },
    {
      "order_id": "46586",
      "patient_id": "12216",
      "pat_name": "Shiavm  Dubey ",
      "pat_mob_num": "9565178888",
      "email": "shivam123@gmail.com",
      "pat_age": "56 Year",
      "pat_gender": "Male",
      "date": "16.01.2024",
      "ts": 1705422205,
      "address": "-hghj, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1452",
      "order_status": "New",
      "order_items": "-"
    },
    {
      "order_id": "46587",
      "patient_id": "12476",
      "pat_name": "Tanmay Bhatt",
      "pat_mob_num": "9999990000",
      "email": "",
      "pat_age": "40 Year",
      "pat_gender": "Male",
      "date": "16.01.2024",
      "ts": 1705424882,
      "address": "-, Kolkata, Kolkata, West Bengal, India",
      "referring_panel_name": "",
      "branch_id": "1452",
      "order_status": "New",
      "order_items": "-"
    },
    {
      "order_id": "46588",
      "patient_id": "12451",
      "pat_name": "Shreemaru Sultan",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "41 Year",
      "pat_gender": "Male",
      "date": "16.01.2024",
      "ts": 1705425829,
      "address": "A, Kolshuli, Kolshuli, West Bengal, India - 556688",
      "referring_panel_name": "",
      "branch_id": "1452",
      "order_status": "New",
      "order_items": "-"
    },
    {
      "order_id": "46616",
      "patient_id": "12120",
      "pat_name": "Anand",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705475124,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "U R/S"
    },
    {
      "order_id": "46627",
      "patient_id": "12448",
      "pat_name": "Mridul Sarkar",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "31 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493644,
      "address": "UMID, Kolshuli, Kolshuli, West Bengal, India - 743329",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "(UG), Testing Lab Panel"
    },
    {
      "order_id": "46628",
      "patient_id": "12505",
      "pat_name": "Balbinder",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "-",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493664,
      "address": "-, Khamar Diar, Khamar Diar, West Bengal, India - 778899",
      "referring_panel_name": "",
      "branch_id": "1263",
      "order_status": "New",
      "order_items": "GH, Testing Lab Panel 2"
    },
    {
      "order_id": "46629",
      "patient_id": "12342",
      "pat_name": "Sumiran Sein",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "37 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493727,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1271",
      "order_status": "New",
      "order_items": "U R/S, Testing Lab Panel, MRI"
    },
    {
      "order_id": "46630",
      "patient_id": "12342",
      "pat_name": "Sumiran Sein",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "37 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493727,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1272",
      "order_status": "New",
      "order_items": "U R/S, Testing Lab Panel"
    },
    {
      "order_id": "46631",
      "patient_id": "12342",
      "pat_name": "Sumiran Sein",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "37 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493728,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1273",
      "order_status": "New",
      "order_items": "MRI"
    },
    {
      "order_id": "46632",
      "patient_id": "12342",
      "pat_name": "Sumiran Sein",
      "pat_mob_num": "",
      "email": "",
      "pat_age": "37 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493730,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1432",
      "order_status": "New",
      "order_items": "-"
    },
    {
      "order_id": "46633",
      "patient_id": "12358",
      "pat_name": "Kartik Sharma",
      "pat_mob_num": "9999119281",
      "email": "",
      "pat_age": "25 Year",
      "pat_gender": "Male",
      "date": "17.01.2024",
      "ts": 1705493794,
      "address": "-, Kolkata, Kolkata, West Bengal, India - 700000",
      "referring_panel_name": "",
      "branch_id": "1271",
      "order_status": "New",
      "order_items": "U R/S, Testing Lab Panel, MRI"
    }
  ]
}

app.get('/api/orders', (req, res) => {
  res.json(sampleData);
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
